### ISSUE TITLE
Upgrade ddmlib and release new version

### ISSUE THREAD

**Issue by mosabua** [rtyley/android-screenshot-lib#1]
http://search.maven.org/#artifactdetails%7Ccom.android.tools.ddms%7Cddmlib%7C22.0%7Cjar

**Comment by rtyley** [comment]
This has been released as v1.9 and is now available on Maven Central:

http://search.maven.org/#search%7Cga%7C1%7Candroid-screenshot

**Comment by mosabua** [comment]
Sweet .. thanks. Will be used in the new android maven plugin release.
