### ISSUE TITLE
Library's license

### ISSUE THREAD

**Issue by gdemiollis** [rtyley/android-screenshot-lib#3]
Hi,

Can you tell me under which license your library is ditributed?

Thank you.

Guilhem

**Comment by rtyley** [comment]
It's hidden away, but the answer is [Apache V2](http://www.apache.org/licenses/LICENSE-2.0):

https://github.com/rtyley/android-screenshot-lib/blob/master/pom.xml#L24-L28

**Comment by gdemiollis** [comment]
Ok cool, Thank you!
